# Generated by Django 2.1.7 on 2019-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190319_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
