# Generated by Django 2.1.7 on 2019-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190319_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
