# Generated by Django 2.1.7 on 2019-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190319_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desired_price',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
