# Generated by Django 2.1.7 on 2019-03-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_order_desired_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_price',
            field=models.CharField(max_length=100),
        ),
    ]
