# Generated by Django 3.0.2 on 2020-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20190321_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
