# Generated by Django 3.0.2 on 2020-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200511_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
