# Generated by Django 3.0.2 on 2020-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
